exclude: ['vendor/bundle', 'node_modules', '.git', '.bundle', '.saas-cache', '.bowerrc', '.gitignore', 'Gemfile', 'Gemfile.lock']
title: Repository of Sharing Knowledge
description: 「知の共有化」に関する資料アーカイブ
show_downloads: false
google_analytics:
theme: jekyll-theme-architect
gems:
  - jekyll-redirect-from
encoding: UTF-8
